default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET
    
default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST
    
default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: POST

default_usuario:
    path: /usuario/{id}
    defaults: { _controller: "AppBundle:Default:usuario", id:null }
    methods: POST

